plugins:
  - rubocop-rails

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.3
  Exclude:
    - "db/schema.rb"
    - "bin/*"

Layout/LineLength:
  Max: 120

Style/StringLiterals:
  EnforcedStyle: single_quotes
