name: loglady-lint

services:
  rubocop:
    image: ruby:3.3.11
    working_dir: /rails
    command: bash -lc "bundle check || bundle install; bundle exec rubocop"
    volumes:
      - .:/rails
      - loglady-lint-bundle:/usr/local/bundle
    networks:
      - loglady-lint

volumes:
  loglady-lint-bundle:

networks:
  loglady-lint:
    name: loglady-lint
